# Generated by Django 3.2.6 on 2021-08-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20210818_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Multiplication', models.TextField()),
                ('division', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='tozih',
        ),
    ]
