 Generated by Django 3.2.6 on 2021-08-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jam_majzur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_number', models.DecimalField(decimal_places=4, max_digits=10)),
                ('second_number', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
