# Generated by Django 3.2.6 on 2021-08-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tozih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multipulation', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='jam_majzur',
        ),
    ]
